package view;

import dao.StudentDAO;
import java.awt.Color;
import javax.swing.*;
import java.net.URL;
import view.panels.AppointmentPanel;
import view.panels.StudentPanel;
import view.panels.CounselorPanel;
import view.panels.FeedbackPanel;
import java.sql.Connection;


public class MainDashboard extends javax.swing.JFrame {


    public MainDashboard(Connection connection) {
        initComponents();
        

        
        tabbedPane.add("Appointments", new AppointmentPanel());
        tabbedPane.add("Students", new StudentPanel(connection));
        tabbedPane.add("Counselors", new CounselorPanel(connection));
        tabbedPane.add("Feedback", new FeedbackPanel(connection));
        
        
        tabbedPane.setBorder(BorderFactory.createMatteBorder(2, 0, 0, 0, new Color(88, 90, 92)));
        
        
        
        
        
        // Set icon image
        URL iconURL = getClass().getResource("/resources/icons/app-icon.png");
        if (iconURL != null) {
            ImageIcon icon = new ImageIcon(iconURL);
            setIconImage(icon.getImage());
        } else {
            System.err.println("Icon not found!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StudentCare");
        setResizable(false);

        tabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabbedPane.setToolTipText("");
        tabbedPane.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
